### ISSUE TITLE
processdata.py met does not have formula

### ISSUE THREAD

**Issue by emarquezz** [SBRG/cobrame#19]
Hi! I've used the build_me_model.ipynb from ecolime and it gives me the next warning:

**/cobrame/core/processdata.py:257 UserWarning: met (generic_tRNA_GAG_glu__L_c) does not have formula**
 
And when I solve it, it gives me a different result than the v 0.0.5 . Do you know why is this happening? I got the new folders from github, followed the instructions to install cobrame and ecolime again , used the new build_me_model.ipynb and solved them with SoPlex. 

Thanks!

**Comment by coltonlloyd** [comment]
Hi,

That warning is expected. It is a weird case where a charged tRNA participates as a metabolite in a MetabolicReaction (GLUTRR, http://bigg.ucsd.edu/universal/reactions/GLUTRR). This warning appears because of the new mass balance checks that were added since v 0.0.5.

The growth rate should be a little slower now (~0.82). This is mostly because we decided to transition to just using the same parameters (unmodeled protein fraction, gam, ngam, etc.) as iJL1678-ME (https://www.ncbi.nlm.nih.gov/pubmed/25227965). There were some corrections detailed in the v 0.0.6 release notes that had a small effect as well.

Let me know if you have any other questions!
