### ISSUE TITLE
Acetate production prediction

### ISSUE THREAD

**Issue by emarquezz** [SBRG/cobrame#20]
Hi! I just noticed that in the v0.0.5, when I variated de UPF value, the acetate production changed. But now, It almost stays the same. Should this be happening? Thank you!

## **v0.0.6**
![image](https://user-images.githubusercontent.com/17349356/33053359-bfdd121a-ce38-11e7-981c-faf214c19afe.png)

## **v0.0.5**
![image](https://user-images.githubusercontent.com/17349356/33053372-d328f32a-ce38-11e7-91a5-6f756440896f.png)

**Comment by coltonlloyd** [comment]
Yes this is expected because we transitioned to using the exact global parameters from PMID:25227965 minus the surface area constraints. 

Version v0.0.5 has acetate overflow at high growth rates because we had imposed an artificial limit on oxygen uptake to 16 mmol/gDW/hr. This was supposed to be a proxy for either reduced respiration activity at high growth rates or for saturation/capacity restrictions of the membrane bound proteins (since these are the two main hypotheses for why acetate overflow occurs).

We thought it was best to remove constraints on oxygen uptake until we fully explore the model parameterization as it pertains to the acetate overflow phenomenon. Sorry for the confusion!
